# === Stage 38: Добавь расширенный набор тестов для ошибок и пограничных случаев ===
# Project: SupportQueue
def test_edge_cases():
    from queue import PriorityQueue
    pq = PriorityQueue()
    pq.put((1, "low"))
    pq.put((3, "high"))
    pq.put((2, "mid"))
    assert pq.get() == (1, "low")
    assert pq.get() == (2, "mid")
    assert pq.get() == (3, "high")
    assert pq.qsize() == 0
    pq.put((3.5, "float"))
    pq.put((3, "int"))
    assert pq.get() == (3, "int")
    assert pq.get() == (3.5, "float")
    pq.put((3, "dup"))
    pq.put((3, "dup2"))
    assert pq.get() == (3, "dup")
    assert pq.get() == (3, "dup2")
    pq.put((float("inf"), "inf"))
    pq.put((float("-inf"), "neg_inf"))
    assert pq.get() == (float("-inf"), "neg_inf")
    assert pq.get() == (float("inf"), "inf")
    pq.put((1e308, "huge"))
    assert pq.get() == (1e308, "huge")
    pq.put((0, "zero"))
    assert pq.get() == (0, "zero")
    pq.put((None, "none"))
    assert pq.get() == (None, "none")
    pq.put((True, "true"))
    assert pq.get() == (True, "true")
    pq.put((False, "false"))
    assert pq.get() == (False, "false")
    print("All edge case tests passed!")
